# === PROFILE TEST ===
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false

# JWT para testes
jwt.secret=TestSecretKey2026
jwt.expiration=3600000

# Desabilitar actuator e swagger em testes
management.endpoints.web.exposure.include=
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
