# === PROFILE PROD ===
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
logging.level.com.studio.core=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN

# Actuator restrito em prod
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Swagger desabilitado em prod
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
