# === PROFILE DEV ===
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.com.studio.core=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Actuator exposto em dev
management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=always

# Swagger habilitado
springdoc.swagger-ui.enabled=true
